### ISSUE TITLE
something problem 

### ISSUE THREAD

**Issue by Ba-hub** [carloswbarros/apk-decompiler#1]
ghosthub@localhost:~/reverse/apk-decompiler$ python3 apk_decompiler.py -a facebook.apk -v 
[+] Decompiling the apk

[+] Creating temp directory
Traceback (most recent call last):
  File "apk_decompiler.py", line 138, in <module>
    main()
  File "apk_decompiler.py", line 134, in main
    decompile_apk(args.apk, args.output_dir, args.verbose)
  File "apk_decompiler.py", line 42, in decompile_apk
    shutil.copy2(apk_path, apk_zip)
  File "/usr/lib/python3.8/shutil.py", line 433, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 376, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib/python3.8/shutil.py", line 326, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: 'temp/facebook.zip'

**Comment by cristea2017** [comment]
`python3 apk_decompiler.py -a facebook.apk` - works 

LOG's:
[+] Decompiling the apk

[+] Creating temp directory
[+] Getting the jar
[+] Decompiling the jar
[+] Reverse engineering the apk
[+] Organizing everything
[+] Moving reverse engineering files
Traceback (most recent call last):
  File "apk_decompiler.py", line 138, in <module>
    main()
  File "apk_decompiler.py", line 134, in main
    decompile_apk(args.apk, args.output_dir, args.verbose)
  File "apk_decompiler.py", line 78, in decompile_apk
    re_list = os.listdir(apk_re)
FileNotFoundError: [Errno 2] No such file or directory: 'temp/b_re'
asd@ReactHotspot apk-decompiler-master % python3 apk_decompiler.py -a b.apk

**Comment by cristea2017** [comment]
> ghosthub@localhost:~/reverse/apk-decompiler$ python3 apk_decompiler.py -a facebook.apk -v
> [+] Decompiling the apk
> 
> [+] Creating temp directory
> Traceback (most recent call last):
> File "apk_decompiler.py", line 138, in
> main()
> File "apk_decompiler.py", line 134, in main
> decompile_apk(args.apk, args.output_dir, args.verbose)
> File "apk_decompiler.py", line 42, in decompile_apk
> shutil.copy2(apk_path, apk_zip)
> File "/usr/lib/python3.8/shutil.py", line 433, in copy2
> copystat(src, dst, follow_symlinks=follow_symlinks)
> File "/usr/lib/python3.8/shutil.py", line 376, in copystat
> _copyxattr(src, dst, follow_symlinks=follow)
> File "/usr/lib/python3.8/shutil.py", line 326, in _copyxattr
> os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
> PermissionError: [Errno 13] Permission denied: 'temp/facebook.zip'

`python3 apk_decompiler.py -a facebook.apk`- works

LOG's:
[+] Decompiling the apk

[+] Creating temp directory
[+] Getting the jar
[+] Decompiling the jar
[+] Reverse engineering the apk
[+] Organizing everything
[+] Moving reverse engineering files
Traceback (most recent call last):
File "apk_decompiler.py", line 138, in
main()
File "apk_decompiler.py", line 134, in main
decompile_apk(args.apk, args.output_dir, args.verbose)
File "apk_decompiler.py", line 78, in decompile_apk
re_list = os.listdir(apk_re)
FileNotFoundError: [Errno 2] No such file or directory: 'temp/b_re'
asd@ReactHotspot apk-decompiler-master % python3 apk_decompiler.py -a b.apk

**Comment by carloswbarros** [comment]
It seems you have a permissions problem, you need to give permissions to the directory where you have your apk file or execute this as a sudo user (which I don't recommend)
