### ISSUE TITLE
Why this?

### ISSUE THREAD

**Issue by dannyfoz** [carloswbarros/apk-decompiler#4]
$ python apk_decompiler.py -a -o HTTP.apk
usage: apk_decompiler.py [-h] -a APK
                         [-o OUTPUT_DIR]
                         [-x ODEX_FILE] [-v]
apk_decompiler.py: error: argument -a/--apk: expected one argument
$ python apk_decompiler.py -a HTTP.apk -o $HOME/apkdiff
[+] Decompiling the apk

[~] Removing old temp directory
[+] Creating temp directory
[+] Getting the jar
[+] Decompiling the jar
[+] Reverse engineering the apk
[+] Organizing everything
[+] Moving reverse engineering files
Traceback (most recent call last):
  File "apk_decompiler.py", line 145, in <module>
    main()
  File "apk_decompiler.py", line 140, in main
    decompile_apk(args.apk, args.output_dir, args.verbose,
  File "apk_decompiler.py", line 81, in decompile_apk
    re_list = os.listdir(apk_re)
FileNotFoundError: [Errno 2] No such file or directory: 'temp/HTTP_re'
$ ls
HTTP      LICENSE.md  apk_decompiler.py  tools
HTTP.apk  README.md   temp
$ cd temp
$ ls
HTTP.zip  HTTP_unziped

**Comment by carloswbarros** [comment]
Maybe the "Reverse engineering the apk" didn't work, try to run the same command but with the -v argument to show a more verbose information. It might help find a clue why it didn't work.
